name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
    
    - name: Build
      run: cargo build --release
    
    - name: Package
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path package
        Copy-Item target\release\miband-heart-rate.exe package\
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: package/*
        token: ${{ secrets.GITHUB_TOKEN }}
